export const NFT=[
    {
        title:"NFT ",
        l1:" NFT Marketplace Development Guide",
        l2:" DAO Enabled NFT Platform",
        l3:" NFT Launchpad Development",
        l4:" Cross-Chain NFT Marketplace",
        l5:" NFT Exchange Development",
        l6:" NFT Minting Platform",
        l7:" NFT Token Development",
        l8:" NFT Layer 2 Development",
        l9:" Multi Chains NFT Support",
        l10:" NFT Staking Platform",
        l11:" NFT - API Integration",
        l12:" Fractional NFT Marketplace",
        l13:" NFT Lending Platform",
        l14:" NFT Loan Platform",
        l15:"  NFT Streaming Platform",
    },
    {
        title:"NFT2 ",
        l1:" NFT Marketplace for music",
        l2:" NFT Marketplace for art ",
        l3:" NFT Marketplace for Sports",
        l4:" NFT Marketplace for Real Estate",
        l5:" NFT Marketplace for memes",
        l6:" NFT Marketplace for Domains",
        l7:" NFT Marketplace for Dreams",
        l8:" NFT in E-commerce",
        l9:" Celebrity NFT Marketplace",
        l10:" NFT for Physical assets",
        l11:" Social Media NFT Marketplace",
        l12:" Community Centric Marketplace",
        l13:" NFT Ticketing Marketplace",
        l14:" Social token marketplace",
    },
    {
        title:"NFT3 ",
        l1:" NFT Marketplace On Ethereum",
        l2:" NFT Marketplace In Matic",
        l3:" NFT Marketplace On BSC",
        l4:" NFT Marketplace On Astar",
        l5:" NFT Marketplace On Avalanche",
        l6:" NFT Marketplace On Cardano",
        l7:" NFT Development In Sidechain",
        l8:" NFT In Flow Blockchain",
        l9:" Solana Based NFT Development",
        l10:" NFT Marketplace In Harmony",
        l11:" NFT Multiverse Development",
        l12:" NFT Marketplace Like Zed Run",
        l13:" NFT Marketplace Like Decentraland",
        l14:" Soulbound Tokens",
    },
    {
        title:"NFT4",
        l1:" NFT Marketplace Like SuperRare",
        l2:" CryptoPunks Like NFTDevelopment",
        l3:" BAYC Like NFT Development",
        l4:" Mekaverse Like NFT Development",
        l5:" Smart Contract Based NFT ",
        l6:" NFT Marketplace Like OpenSea",
        l7:" NFT Marketplace Like Solsea",
        l8:" NFT Marketplace Like Rarible",
        l9:" NFT Marketplace Like NBA Top Shot",
        l10:" NFT Marketplace Like Foundation",
        l11:" NFT Marketplace Like Nifty Gateway",
        l12:" NFT Marketplace Like Terra Virtua",
        l13:" NFT Marketplace Like Royal",
        l14:" NFT Marketplace Like Sorare",
    },
    {
        title:"NFT5",
        l1:" Move To Earn NFT Platform",
        l2:" Crypto Dynasty Like NFT Game ",
        l3:" NFT Game Like DungeonSwap",
        l4:" NFT Game Like Crypto Kitties",
        l5:" F1 Delta Time Like NFT Game ",
        l6:" Evolution Land Like NFT Game ",
        l7:" NFT Game Like Prospectors",
        l8:" NFT Marketplace Like Gods Unchained",
        l9:" NFT Marketplace Like Polkacity",
        l10:" NFT Game Like My Crypto Heroes",
        l11:" LudoNFT Like Game Development",
        l12:" Gaming Platform In Sandbox",
        l13:" NFT Racing Game Development service",
        l14:" NFT Game like Revvracing",
    },

]

export const DEFI=[
    {
        title:"DEFI ",
        l1:"PancakeSwap Like Dex Development",
        l2:" Whitelabel Swap Exchange Development",
        l3:" DeFi Staking Platform Development",
        l4:" Defi Yield Farming Development",
        l5:" DEFI Lending And Borrowing Platform",
        l6:" DeFi Smart Contract Development Services",
        l7:" DeFi Token Development Services Company",
        l8:" DeFi Insurance Platform Development Services",
        l9:" Defi Synthetic Assets Development",
        l10:" DeFi Solutions For ECommerce ",
    },
    {
        title:"DEFI ",
        l1:"Defi Tokenization Development",
        l2:" Defi Crowdfunding Platform",
        l3:" Defi Real Estate Platform",
        l4:" Defi ICO Development Company",
        l5:" Decentralized Exchange Like Uniswap",
        l6:" DeFi Protocol Development Like Yearn Finance",
        l7:" Decentralized Exchange Like 1inch2",
        // l8:" DeFi Insurance Platform Development Services",
        // l9:" Defi Synthetic Assets Development",
        // l10:" DeFi Solutions For ECommerce ",
    },

]

export const ICO=[
    {
        title:"ICO/STO/IDO ",
        l1:"ICO Website Design",
        l2:" Security Token Offering",
        l3:" STO Exchanges",
        l4:" STO Smart Contracts",
        l5:" ETO Development",
        l6:" Tokenized Asset Offering",
        l7:" IDO Token Launchpad",
        l8:" Launchpad Development",
        l9:" Polkastarter",
        l10:" IFO Development Services ",
        l11:" ILO Development",
    },
    {
        title:"ICO/STO/IDO ",
        l1:"IDO Launchpad On BSC",
        l2:" IDO Launchpad On Ethereum",
        l3:" IDO Launchpad On Solana",
        l4:"IDO Launchpad On Cardano",
        l5:" IDO Launchpad In Multichain",
        l6:" IDO Launchpad On Polygon",
        l7:" Binance Smart Chain",
        l8:" Token Development Like BEP - 20",
        l9:" Smart Contract MLM On BSC",
        l10:" Art Tokenization ",
        l11:" Tokenization Platform",
    }
]

export const Crypto=[
    {
        title:"Crypto ",
        l1:"Decentralized Stablecoin Development",
        l2:" Masternode Coin Development",
        l3:" P2P Like Local Bitcoin",
        l4:" Metamask Like Wallet Development",
        l5:" Hybrid Cryptocurrency Exchange Development",
        l6:" Cryptocurrency Exchange Like Wazirx",
        l7:" Cryptocurrency Exchange Like Binance",
        l8:" Cryptocurrency Exchange Like Coinbase",
    },
    {
        title:"Crypto ",
        l1:"Crypto Exchange Algo Trading",
        l2:" Cryptocurrency Litigation Services",
        l3:" Cryptocurrency Exchange Legal",
        l4:"Cryptocurrency Exchange License Offering",
        l5:" Bitcoin Mining Software",
        l6:" Cryptocurrency MLM Software",
        l7:" Cryptocurrency ATM Software",
        l8:" Safemoon Like Token Development",
    },
]

export const Blockchain=[
    {
        title:"Blockchain ",
        l1:"Private Blockchain Development",
        l2:" POC Development",
        l3:" Smart Contract Audit",
        l4:" Sports Betting DApp",
        l5:" Directed Acyclic Graph",
        l6:" Blockchain Payment Remittance ",
        l7:" Stellar Remittance Platform ",
        l8:" Ethereum Smart Contract ",
        l9:" Solidity Development",
        l10:" Quorum Explorer",
        l11:" Ethereum Token Development",
        l12:" Tron DApps Development",
        l13:" Tron Token Development",
    },
    {
        title:"Blockchain ",
        l1:"Kusama Blockchain Development",
        l2:" HyFi Blockchain Development",
        l3:" Blockchain Consulting",
        l4:" Hyperledger Development",
        l5:" Stellar Blockchain Development",
        l6:" Hashgraph Development",
        l7:" Tezos DApp Development",
        l8:" Blockchain For Finance",
        l9:" Blockchain For Cybersecurity",
        l10:" Supply Chain Development",
        l11:" Blockchain IoT Development",
        l12:" EMR And EHR Software Development",
        l13:" Blockchain For Pharma Industrye",
    },

]

export const Marketing=[
    {
        title:"Marketing ",
        l1:"NFT Marketplace Marketing Services",
        l2:" NFT Collectibles Marketing",
        l3:" NFT Discord Marketing",
        l4:" NFT Telegram Marketing",
        l5:" NFT Influencer Marketing",
        l6:" NFT PR/Media Marketing",
        l7:" NFT Listing Services",
        l8:" Discord Marketing",
    },
    {
        title:"Marketing ",
        l1:"ICO Marketing Guide",
        l2:" ICO Bounty Marketing",
        l3:" ICO Youtube Influencer ",
        l4:" ICO Community Marketing",
        l5:" ICO Telegram Marketing",
        l6:" ICO Influencer Marketing",
        l7:" Listing Services",
        l8:" ORM Services",
    },
]